### ISSUE TITLE
Providing request object in websocket view

### ISSUE THREAD

**Issue by davidh-ssec** [housleyjk/aiopyramid#11]
I have a use case where I need access to some configuration values from my INI file inside a websocket view. I've looked through the code and the `ws` object and nothing jumped out to me as having the registry/settings information in it. Is there a recommended way of doing this or does something need to be added to the WebsocketMapper? And I don't know if this is a common thing, but wouldn't you also need the request object if you passed URL parameters?

**Comment by housleyjk** [comment]
That is a very reasonable request, and a solution already exists. Use a class-based view such as the provided [WebsocketConnectionView](http://aiopyramid.readthedocs.org/en/latest/_modules/aiopyramid/websocket/view.html#WebsocketConnectionView). The mapper changes the view callable to accept a websocket object instead of a request or context/request pair, but underlyingly, it's still the same system. So, class-based views that use the mapper will need to provide a `__call__` method that takes a `ws` parameter (instead of the default noargs), but your `__init__` still takes a context/request as usual.

Does that make sense? I should probably update the documentation with an example of this. Thank you for bringing it up!

**Comment by davidh-ssec** [comment]
Ah yes, that makes sense...and is kind of obvious if I would have thought about it longer. I never seem to think of class-based view right away for some reason. Thanks, this looks like it should work.
