### ISSUE TITLE
Gunicorn and uWSGI websocket interface inconsistencies

### ISSUE THREAD

**Issue by circlingthesun** [housleyjk/aiopyramid#12]
When running `yield from ws.recv()` on Python 3.4 UWSGIWebsocketMapper returns bytes but WebsocketMapper returns a str. Is this desired behaviour?

On a related note, it would be nice if you could import WebsocketMapper from aiopyramid.websocket.config without having to know whether you are using Gunicorn or uWSGI. I'd like to be able to run gUnicorn when testing locally and uWSGI in production.

**Comment by housleyjk** [comment]
I would consider that undesirable behavior. Since we don't have access to the raw Websocket frame in either case, it's not possible to know for sure whether the message is intentionally binary or not. UWSGI will always send binary. Should I attempt to decode the uwsgi message as utf8, and if that fails send it as binary? 99% of the time that will match the behavior of the websockets library and give callers strings most of the time, which is usually what they are after. However, it means that binary data from UWSGI that happens to be utf8 but was sent with a binary flag will be interpreted as utf8 instead of matching the frame, which could cause confusion for some. Alternatively, an absolutely consistent approach would be to match the UWSGI behavior and instead encode strings from websockets to bytes and make the caller decide whether to decode to a str. The downside is that this approach would make the common case much less convenient for callers (you would have to decode manually all of the time). 

What do you think? Which way works best for you? I'm leaning towards matching the behavior of gunicorn/websockets backend and just documenting the behavior.

The reason the mappers are the way they are is because I didn't want to decide for users which approach would be preferred. However, it's easy to do what you want as it is now:

```python
try:
    import uwsgi
    from aiopyramid.websocket.config import UWSGIWebsocketMapper
    WSMapper = UWSGIWebsocketMapper
except ImportError:
    from aiopyramid.websocket.config import WebsocketMapper
    WSMapper = WebsocketMapper

# Use WSMapper elsewhere
```

With that, you can just use the `WSMapper` variable instead and it will be gunicorn in environments that don't have uwsgi installed.

**Comment by circlingthesun** [comment]
Thanks, I figured out the import trick. It was really just a once off annoyance. You could do that inside the __init__.py file, but I guess its better to be explicit.

I'm leaning towards binary data. That will however break things for existing gunicorn users. So encoding data as utf8 is probably better default behaviour. It would be nice to have a switch though.

This is actually the reason I submitted #13. I was using gUnicorn and then switched to uWSGI which broke things. Only there was as no way to tell what went wrong as exceptions were being swallowed.
