### ISSUE TITLE
add_request_method and asyncio-redis

### ISSUE THREAD

**Issue by dfee** [housleyjk/aiopyramid#20]
I'm having a difficult time understanding how to add a connection to asyncio-redis to the request method using config.add_request_method.

Here's my `connect_redis` function:
```
import asyncio
import asyncio_redis


async def connect_redis():
    # Create connection
    return asyncio_redis.Connection.create(host='redis', port=6379)
```

Here's how I'm connecting it:
```
from myproj.hooks.request import connect_redis


def includeme(config):
    # Request Methods
    config.add_request_method(connect_redis, name='redis')
```

And finally, here's how I'm attempting to access it:

```
import asyncio

from aiopyramid.websocket.config import WebsocketMapper
from aiopyramid.websocket.view import WebsocketConnectionView

@view_config(route_name='listen')
class ListenWebsocket(MyWebsocket):

    def on_open(self):
        # Create subscriber.
        subscriber = yield from self.request.redis.start_subscribe()

        # Subscribe to channel.
        yield from subscriber.subscribe(['our-channel'])

        # Inside a while loop, wait for incoming events.
        while True:
            reply = yield from subscriber.next_published()
            msg = 'Received: {reply.value} on channel ${reply.channel}'.format(
                reply=reply
            )
            print(msg)
            yield from ws.send(msg)

        # When finished, close the connection.
        self.request.redis.close()
```

But this yields the following error:
`AttributeError: 'function' object has no attribute 'start_subscribe'`

How would you suggest I provide access to this connection?

**Comment by dfee** [comment]
Some additional background might be helpful here:

I can move the connection code into the `on_open` method. However, I'm concerned that I shouldn't be creating additional redis connections for every connection. I also want to publish to the pubsub from sync code. Would I need to use both `pyramid_redis` (of course, just `redis` would work) in that code and `asyncio_redis` in my async views?

**Comment by housleyjk** [comment]
Since connections can go stale, it's generally best not to have one live a long time in a WebSocket. I haven't been in a project with the `asyncio_redis` code for a while, but I believe that is still true. `asyncio_redis` might solve that under the hood. Anyway, what I have done in the past, and what is probably still a good idea is to use a [pool](https://github.com/jonathanslenders/asyncio-redis#connection-pooling). Since the pool is shared by all parts of the site, it's fine to create it synchronously in your app constructor (e.g. `main` or `includeme`):

``` python
pool = asyncio.get_event_loop().run_until_complete(
    asyncio_redis.Pool.create(poolsize=5)
)

def add_redis(request):
    return pool

config.add_request_method(add_redis, 'redis', reify=True)
...

# Then in your code, use the pool on the request like
yield from self.request.redis.set( # you can treat a pool pretty much like a connection
    self.context.source,
    json.dumps(self.values),
    expire=60 * 60 * 24,  # one day
)
```

Regarding the pubsub, as you have noticed, listening for more than one message requires a loop. This means you have two options: either 1) schedule a parallel coroutine task, 2) run the subscriber in a separate thread using the executor and regular synchronous redis.

I couldn't find a code example for this, but in Aiopyramid, there is only one event loop (unless you change that). So, I would do something like this using [ensure_future](https://docs.python.org/3/library/asyncio-task.html#asyncio.ensure_future): 

```python

async def listen(ws, *channels):
    # Create subscriber.
    subscriber = yield from ws.request.redis.start_subscribe()
        
    # Subscribe to channel.
    yield from subscriber.subscribe(*channels)
    
    # Inside a while loop, wait for incoming events.
    while True:
        reply = yield from subscriber.next_published()
        msg = 'Received: {reply.value} on channel ${reply.channel}'.format(
            reply=reply
        )
        print(msg)
        yield from ws.send(msg)

...
# In on_open start the task
self.subscriber_task = asyncio.ensure_future(listen(self))
...
# In on_close, cancel the task
self.subscriber_task.cancel()

```
That's of course not perfect, but it's a start, and hopefully it should solve your problem.
