### ISSUE TITLE
Appropriate usage of synchronize is unclear

### ISSUE THREAD

**Issue by dfee** [housleyjk/aiopyramid#22]
I've made a small revision to a project generated by the aio_websocket scaffold by:
1. turning `home` into a class
2. moving the sleep function into an async function that sleeps.

```
import asyncio

from pyramid.view import view_config
from aiopyramid.websocket.config import WebsocketMapper
from aiopyramid.helpers import synchronize


class Home:
    def __init__(self, context, request):
        self.context = context
        self.request = request

    @synchronize
    async def sleep(self):
        await asyncio.sleep(1)

    @view_config(
        route_name='home',
        request_method='GET',
        renderer='xyz:templates/home.jinja2',
    )
    def get(self):
        wait_time = float(self.request.params.get('sleep', 0.1))
        self.sleep()
        # yield from asyncio.sleep(wait_time)
        return {'title': 'xyz websocket test', 'wait_time': wait_time}


@view_config(route_name='echo', mapper=WebsocketMapper)
@asyncio.coroutine
def echo(ws):
    while True:
        message = yield from ws.recv()
        if message is None:
            break
        yield from ws.send(message)
```

However, I get the following error message:

```
  File "/var/www/xyz/env/lib/python3.5/site-packages/pyramid/viewderivers.py", line 137, in _class_view
    response = getattr(inst, attr)()
  File "/var/www/xyz/xyz/views.py", line 24, in get
    self.sleep()
  File "/var/www/xyz/env/lib/python3.5/site-packages/aiopyramid/helpers.py", line 104, in _wrapped_coroutine
    SCOPE_ERROR_MESSAGE.format(coroutine_func)
aiopyramid.exceptions.ScopeError:
Synchronized coroutine <function Home.sleep at 0x7fef60a867b8> called in the parent
greenlet.

This is most likely because you called the synchronized
coroutine inside of another coroutine. You need to
yield from the coroutine directly without wrapping
it in aiopyramid.helpers.synchronize.

If you are calling this coroutine indirectly from
a regular function and therefore cannot yield from it,
then you need to run the first caller inside a new
greenlet using aiopyramid.helpers.spawn_greenlet.
```

Following from the [architecture guidelines](http://aiopyramid.readthedocs.io/approach.html), I assume:
- the worker is the parent (coroutine)
- Home.get is the normal function (not a coroutine)
- Home.sleep is the `some_async_task`.

How should I be using `synchronize`?

**Comment by dfee** [comment]
It seems what's appropriate is to not use synchronize here, but instead replace the __call__ method on the Class Based View as such:

```
class Home:
    def __init__(self, context, request):
        self.context = context
        self.request = request

    async def sleep(self):
        await asyncio.sleep(1)

    @view_config(
        route_name='home',
        request_method='GET',
        renderer='xyz:templates/home.jinja2',
    )
    async def get(self):
        wait_time = float(self.request.params.get('sleep', 0.1))
        await self.sleep()
        return {'title': 'xyz websocket test', 'wait_time': wait_time}

    async def __call__(self):
        return await super().__call__()
```

**Comment by housleyjk** [comment]
So the reak question is whether the `Home` class needs to be a regular synchronous view or a coroutine view. Your first example looks like a synchronous view (although the dummy code doesn't _have_ to be synchronous, you could do that in an async view). Your second example is an aysnc view where the class `Home` is a callable coroutine. Another way to achieve what you have there is

``` python
@asyncio.coroutine
class Home:
    def __init__(self, context, request):
        self.context = context
        self.request = request

    async def sleep(self):
        await asyncio.sleep(1)

    @view_config(
        route_name='home',
        request_method='GET',
        renderer='testy:templates/home.jinja2',
    )
    async def get(self):
        wait_time = float(self.request.params.get('sleep', 0.1))
        await self.sleep()
        return {'title': 'testy websocket test', 'wait_time': wait_time}
```

I like the decorator better than overriding `__call__` if all you want is to make the class a coroutine.

Anyway, I wouldn't worry about `synchronize`. The `synchronize` wrapper is for interfacing mostly with framework code that is running in a greenlet. This is because Pyramid is not naturally an async framework, so places where you want to give a coroutine to the framework need to be wrapped in `synchronize` so that the framework can "call them normally."

However, this trick only works inside of a greenlet, and your original view is not framework code, it's not running in a greenlet. Instead, if it's a synchronous view like that, it will be run in a separate thread. In a view running in a separate thread, you can use regular Python code, but you can't directly use async code without spawning a new greenlet to yield back up to where the event loop is running. If you look at the example in [architecture](http://aiopyramid.readthedocs.io/approach.html#architecture), you will see that `spawn_greenlet` is used to make the normal synchronous function `normal_function` into a coroutine that runs the sync code in a greenlet. In other words, you only need `synchronize` when you have a world that is async >> sync (greenlet) >> async (this async code needs to be synchronized because it will be called in a sync environment). A simple view like your first example is run in a thread, so it's just a sync environment already, and if you need to wait on a coroutine (like the one created by `spawn_greenlet`) there, you can just use the regular `run_until_complete` methodology.

That was probably a lot, and it probably didn't make a lot of sense without you going through the code a lot yourself.

But my point is, you probably don't need to worry about that for your use-case. If you have blocking code, use a synchronous view. If you have async code, use an async view. If you have both, use an async view and delegate out any blocking work to the executor using the `use_executor` decorator or vanilla asyncio. It's best not to try working the other way (running async code inside of a synchronous view), it's no more expensive to call out to the executor yourself than to have `Aiopyramid` do it anyway. You can think of async views as being "preferred."

Hopefully that makes sense. For your simple example, just use an async view like you sent me or as I demonstrated above, and don't worry about `synchronize` until you find yourself interfacing with some part of the `Pyramid` framework, that's where you may need it.

Please respond to let me know if this helps, if not, I can always try to confuse you more. :smile:

**Comment by dfee** [comment]
I guess, re-reviewing, I'm unclear why the class needs to be async. If I use aiopyramid.helpers.is_generator, the view `Home.get` returns `True`.

Yet, when I try and actually call that view (using `@view_config(renderer='json', …)`, I get something like:
```
TypeError: <coroutine object Home.get at 0x7f54a9a0c888> is not JSON serializable
```

**Comment by dfee** [comment]
I found the problem, and it's a bug in aiopyramid's [`CoroutineOrExecutorMapper`](https://github.com/housleyjk/aiopyramid/blob/8aef5f4f8c823d138f36b68df2ad40a8b5adb6a3/aiopyramid/config.py#L99).

We ought to be checking [`DefaultViewMapper.attr`](https://github.com/Pylons/pyramid/blob/master/pyramid/viewderivers.py#L61) not `__call__` specifically.

The better code looks like this:
```
        if (
            asyncio.iscoroutinefunction(original) or
            is_generator(original) or
            # is_generator(
            #     getattr(original, '__call__', None)
            # ) or
            is_generator(
                getattr(original, self.attr, None)
            )
        ):
```

If you agree, I'll submit a pull request.

**Comment by housleyjk** [comment]
Does this change still allow for `__call__` to be used as the default view method on a class?

**Comment by dfee** [comment]
With those lines commented out, it does not support `__call__`. However, my [branch](https://github.com/dfee/aiopyramid/blob/master/aiopyramid/config.py) doesn't have those lines commented out.

LMK if you want a PR.

**Comment by dfee** [comment]
As for synchronize, I'm still not entirely clear. However, this seems to exemplify how to:
1. call async code from a sync view function
2. call io heavy code from an async view function

```
import asyncio

from aiopyramid.helpers import use_executor
from pyramid.view import view_config


async def aio_work():
    print('about to sleep')
    await asyncio.sleep(2)
    print('awake')


@use_executor
def work_in_thread():
    print('working in thread')


@view_config(route_name='api.test.sync', renderer='json')
def sync_view(request):
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    loop.run_until_complete(aio_work())
    return {}


@view_config(route_name='api.test.async', renderer='json')
async def async_view(request):
    await work_in_thread()
    return {}
```

**Why would I want to call out to async code in a sync function?**
Notice that I'm creating an event loop in the thread. This is because I might be using something like asyncio-redis to do work, but I can't await it because it's a sync function.

**Why would I want to call out to sync code in an async function?**
I'm using `@use_executor` because I might want to get request.user that hits a sqlalchemy database.

Please let me know your thoughts on whether any of your helper methods would accomplish this same thing, or whether you disagree with either of these approaches. Thanks!

**Comment by dfee** [comment]
I take back part of what I just said (**Why would I want to call out to async code in a sync function?**). I won't be able to make requests on asyncio-redis unless I use an async view function. This is because a sync view function won't have access to the loop that asyncio-redis is running on.

So, I guess that's kind of a bummer.

As per **Why would I want to call out to sync code in an async function?**, I can still do postgresql calls within @use_executor as you've recommend elsewhere.

**Comment by housleyjk** [comment]
A sync view function still has access to the event loop, just not as part of a coroutine chain. And I agree, it makes more sense to use an async view and call sync code with `@use_executor` rather than to try to work  the other way.

**Comment by housleyjk** [comment]
The design of `asyncio` is to have one event loop for all threads (i.e. one loop per process, this can be overriden by customizing the event loop). So simply calling `asyncio.get_event_loop()` will do it. It is possible to schedule a coroutine from a separate thread, https://docs.python.org/3/library/asyncio-dev.html#concurrency-and-multithreading. I'm sorry, I should have mentioned that earlier.

**Comment by dfee** [comment]
Thanks. [This answer from StackOverflow](http://stackoverflow.com/a/32586795/465164) was helping in understanding that a bit further. It seems that to schedule a task from a thread, you need to pass the loop to the sync function:

```
def target(loop, timeout=None):
    future = asyncio.run_coroutine_threadsafe(add(1, b=2), loop)
    return future.result(timeout)

async def add(a, b):
    await asyncio.sleep(1)
    return a + b

loop = asyncio.get_event_loop()
future = loop.run_in_executor(None, target, loop)
assert loop.run_until_complete(future) == 3
```

However, it doesn't seem we're attaching the event loop to the request in [AsyncioMapperBase](https://github.com/housleyjk/aiopyramid/blob/master/aiopyramid/config.py#L31), and so I'm not sure how views will be aware of the parent event loop. Thoughts?

**Comment by housleyjk** [comment]
Here is the relevant information about event loops per thread. https://docs.python.org/3/library/asyncio-eventloops.html#event-loop-policies-and-the-default-policy. It looks like I got it wrong. I wonder if the default policy was changed in 3.5, my memory is from 3.4 (either that or I probably just remembered wrong 😸). 

Anyway, since each thread gets it's own event loop, I would just use `run_until_complete` with that event loop if you need the thread to wait until some coroutine is complete. I'm not sure I want to build into Aiopyramid a location for the event loop.

For whatever thread you are in, you can get the event loop with `asyncio.get_event_loop()`. So, I'm thinking if you don't want a second event loop in the executor thread, or you absolutely need to run some coroutine on the primary event loop, then you need to pass the primary loop in somehow to the thread. That means getting the event loop with `asyncio.get_event_loop()` somewhere in your primary thread (like the __init__ of your view class, or in an async view, globally, or as you seem to suggest, adding a reified request method that sets the loop on the request, if you like using the request to share data. Then, reference the loop or request with the loop on it in your executor-based view or function.

Do you need an example of putting the loop on the request?

**Comment by dfee** [comment]
OK. I've created a decorator @use_loop to schedule tasks in the loop from executor functions. While I haven't specifically tried it with aiopyramid, it works with regular Python 3.5. Check it out:

```
import asyncio
import concurrent
from datetime import datetime
import functools
import inspect

SLEEP_DURATION = 3

def use_loop(func=None, blocking=True, timeout=None):
    @functools.wraps(func)
    def inner(ins, *args, **kwargs):
        fut = asyncio.run_coroutine_threadsafe(
            func(ins, *args, **kwargs),
            ins.loop
        )
        if blocking:
            return fut.result(timeout)
        return fut
    
        func(*args, **kwargs)
            
    if func is not None:
        return inner
  
    else:
        @functools.wraps(func)
        def partial_inner(func):
            return use_loop(func, blocking=blocking, timeout=timeout)   
        return partial_inner


def do_log(msg):
    fn_name = inspect.stack()[1].function
    print('[{}] <{}> {}'.format(
        datetime.now().strftime('%H:%M:%S'),
        fn_name,
        msg,
    ), flush=True)


class MyClass:
    def __init__(self):
        self.loop = asyncio.get_event_loop()

    @use_loop(blocking=False)
    async def aio_non_blocking(self, value):    
        do_log('sleeping')
        await asyncio.sleep(value)
        do_log('awake')
        return 'done'

    @use_loop
    async def aio_blocking(self, value):
        do_log('sleeping')
        await asyncio.sleep(value)
        do_log('awake')
        return 'done'

    @use_loop(timeout=SLEEP_DURATION-1)
    async def aio_blocking_timeout(self, value):
        do_log('sleeping')
        await asyncio.sleep(value)
        do_log('awake')
        return 'done'

    def test_non_blocking(self, value=SLEEP_DURATION):
        do_log('calling aio_non_blocking')
        result = self.aio_non_blocking(value)
        do_log('returning result from aio_non_blocking')
        return result

    def test_blocking(self, value=SLEEP_DURATION):
        do_log('calling aio_blocking')
        result = self.aio_blocking(value)
        do_log('returning result from aio_blocking')
        return result

    def test_blocking_timeout(self, value=SLEEP_DURATION):
        do_log('calling aio_blocking_timeout')
        result = self.aio_blocking_timeout(value)
        do_log('returning result aio_blocking_timeout aio_blocking')
        return result


def test(mc):
    # import ipdb; ipdb.set_trace()
    do_log('Test Blocking Timeout')
    try:
        tbt_result = mc.test_blocking_timeout()
    except concurrent.futures._base.TimeoutError as e:
        assert 'tbt_result' not in locals()
        do_log('tbt_result not available due to timeout')        
    
    do_log('Test Blocking')
    tb_result = mc.test_blocking()
    assert tb_result == 'done'
    do_log('tb_result: {}'.format(tb_result))

    do_log('Test Non-Blocking')
    tnb_result = mc.test_non_blocking()
    do_log('tnb_result: {}'.format(tnb_result, tnb_result.done()))
    assert isinstance(tnb_result, concurrent.futures._base.Future)
    tnb_result.result(None) # None allows for tnb_result to Finish
    do_log('tnb_result: {}: {}'.format(tnb_result, tnb_result.result()))
    do_log('Tests Complete')




mc = MyClass()
loop = asyncio.get_event_loop()
loop.run_until_complete(loop.run_in_executor(None, test, mc))
```

That returns:
```
[02:38:18] <test> Test Blocking Timeout
[02:38:18] <aio_blocking_timeout> awake
[02:38:18] <test_blocking_timeout> calling aio_blocking_timeout
[02:38:18] <aio_blocking_timeout> sleeping
[02:38:20] <test> tbt_result not available due to timeout
[02:38:20] <test> Test Blocking
[02:38:20] <test_blocking> calling aio_blocking
[02:38:20] <aio_blocking> sleeping
[02:38:21] <aio_blocking_timeout> awake
[02:38:23] <aio_blocking> awake
[02:38:23] <test_blocking> returning result from aio_blocking
[02:38:23] <test> tb_result: done
[02:38:23] <test> Test Non-Blocking
[02:38:23] <test_non_blocking> calling aio_non_blocking
[02:38:24] <test_non_blocking> returning result from aio_non_blocking
[02:38:24] <aio_non_blocking> sleeping
[02:38:24] <test> tnb_result: <Future at 0x7f6a55e23a90 state=pending>
[02:38:27] <aio_non_blocking> awake
[02:38:27] <test> tnb_result: <Future at 0x7f6a55e23a90 state=finished returned str>: done
[02:38:27] <test> Tests Complete
```

I believe this is a fairly elegant solution. MyClass is simply a placeholder for View. What are your thoughts?

**Comment by housleyjk** [comment]
That's cool, there looks like there is a call after return:

``` python
...
        if blocking:
            return fut.result(timeout)
        return fut

        func(*args, **kwargs)
...
```
I think this is just the sort of development that fits well with this library. I don't want to include it directly in the lib, but I think it's a nice technique to have. I don't think it's the only solution, but it seems like a good one to me. Maybe you should make a public gist of this so it's not as hidden from the world?
