### ISSUE TITLE
(Question) Room chat with redis-py and websockets

### ISSUE THREAD

**Issue by qwexvf** [housleyjk/aiopyramid#25]
hi housleyjk, thanks for a great project.
and sorry that is even not a issue.
i got in trouble need help.

i was trying to make room chat with redis-py and websockets

```
@view_config(route_name='socket', mapper=WebsocketMapper)
class WebSocket(WebsocketConnectionView):
    def __init__(self, context, request):
        super().__init__(context, request)
        redis = RedisClient()
        self.client = redis.client
        self.pubsub = redis.pubsub
        self.room = None
        self.subscribed = False
        self.thread = None
        self.user_data = {}

    @asyncio.coroutine
    def on_open(self):
        # check if client became with room id
        if not self.request.matchdict['id']:
            yield from self.send(json.dumps({'status': 1, 'msg': 'No room id!'}))
            return
        self.room = str(self.request.matchdict['id'])

    def on_messages_published(self, message):
        # sounds confusing but nothing special.
        encode = json.dumps(bytes(message['data']).decode())
        yield self.ws.send(encode)

    def sub(self, room):
        # Subscribe to a room with callback
        self.pubsub.subscribe(**{room: self.on_messages_published})
        self.subscribed = True
        self.thread = self.pubsub.run_in_thread(sleep_time=0.001)

    @asyncio.coroutine
    def on_message(self, data):
        decode = json.loads(data)
        if decode['type'] == 'join':
            if self.subscribed:
                return
            # join room
            self.sub(self.room)
        elif decode['type'] == 'chat':
            message = json.dumps({
                'type': 'chat',
                'user': decode['user'],
                'msg': decode['msg']
            })
            self.client.publish(self.room, message)

    @asyncio.coroutine
    def on_close(self):
        print("Disconnected: ", self)
        self.client.publish(self.room, json.dumps({'type': 'leave', }))
        self.pubsub.unsubscribe(self.room)
        self.subscribed = False
        self.thread.stop()

```

this is my code atm but it wont work anyways.
do you have a alternative way to do a chat room?

Thanks Marcelo.

**Comment by housleyjk** [comment]
It looks like the `on_messages_published` method needs to be a coroutine because you are trying to send out a message on the websocket in it. However, I'm guessing that run_in_thread won't take a corountine. Since you are running the subscriber in another thread, you probably need to schedule the coroutine in your subscriber, probably with `run_until_complete`. Check out [this](https://docs.python.org/3/library/asyncio-task.html#example-hello-world-coroutine) example. However, you will want to verify whether a `websockets` object is thread-safe.

Alternatively, you can look at asyncio-redis for pubsub. 

Let me know if this helps.

**Comment by dfee** [comment]
A quick note – I've gone back from using `asyncio-redis` to regular `redis-py` with redis commands executed within an executor, using `aiopyramid.helpers.use_executor` as `@use_executor`. I did that because I wanted to share my redis connection with non-async code, and using an async version got painful.

One more thing, if you need to pass data between an executor and the main loop, you can use a library like [janus](https://github.com/aio-libs/janus).

**Comment by qwexvf** [comment]
@housleyjk 
thanks for your advice really appreciate it.
its a shame to say that but i tried to do what your saying but i couldn't do nothing haha.
could you please give me a example ? thanks.

@dfee 
thanks for your advice too!
i would try it after trying @housleyjk method! thanks!

**Comment by housleyjk** [comment]
janus looks nifty. @qwexvf, dfee just corrected me, there is an independent event loop for each thread https://docs.python.org/3/library/asyncio-eventloops.html#event-loop-policies-and-the-default-policy. 

So, I would try something like this:

```python

    def on_messages_published(self, message):
        """ Warning: This thread blocks, don't call it in the main thread. """
        loop = asyncio.get_event_loop() # gets the event loop for this thread
        loop.run_until_complete(self.respond(message)) # blocks the thread until the message is sent, which is fine because we have our own thread here, right?

   @asyncio.coroutine
   def respond(self, message):
        encode = json.dumps(bytes(message['data']).decode())
        yield from self.ws.send(encode)

    def sub(self, room):
        # Subscribe to a room with callback
        self.pubsub.subscribe(**{room: self.on_messages_published})
        self.subscribed = True
        self.thread = self.pubsub.run_in_thread(sleep_time=0.001)

```

I have not tested this example, but unless you know you need to send a coroutine between threads, I would do it this way. Let me know if this helps!

**Comment by qwexvf** [comment]
Hi @housleyjk, Thank you for helping me out!
I tried your method and it returned this error. I can feel that we are pretty close to do this one!
```RuntimeError: There is no current event loop in thread 'Thread-1'.```

this is the full error log and my whole code.
http://pastebin.com/PdP7hqve

Thanks again. Marcelo

**Comment by dfee** [comment]
@qwexvf you should look at the my response to accessing the event loop from an executor function [here](https://github.com/housleyjk/aiopyramid/issues/22#issuecomment-253695310).

**Comment by housleyjk** [comment]
Dfee is correct if you want to reuse the existing event loop. Let me see if I can make a quick fix to the example using a new loop.

```python

    def on_messages_published(self, message):
        """ Warning: This thread blocks, don't call it in the main thread. """
        loop = asyncio.new_event_loop() # If your project is performance dependent, consider benchmarking the cost of this new creation to see if it is worth risking concurrency issues to reuse and existing loop
        loop.run_until_complete(self.respond(message)) 
```

**Comment by qwexvf** [comment]
hi, @dfee, @housleyjk. thanks both of you!

@housleyjk your method worked!!! im gonna do something like stress test then post the result here for people who may use this method. and i'm definitely going to start learning more about asyncio and threading. thanks a lot.

@dfee i'm gonna try your method too then post the result here. it looks very simple and easy!
thank you very much!!!

Finally, if i want a background worker(thread?) that send a message to client i can do in the same way ?

**Comment by housleyjk** [comment]
The first issue is easy. If `sub()` is never called (which is possible any time there are no join messages), `self.thread` will be none. So, you need to handle that condition. 

The second issue, I'm not sure exactly what is causing it. However, that error is one that you normally have to handle when calling `send()` or `recv()`. So, I think you should simply handle it as well. To theorize, I think what is happening is that the pubsub thread is trying to send on the connection after it's closed but before the thread is terminated. It's a reasonable case.

**Comment by qwexvf** [comment]
@housleyjk thank very much. everything is working but except the publish thing after we close the socket connection. i want to notice that user disconnected from the lobby or room.
handling those `send()` and `recv()` will be a solution? and don't know how either haha..

**Comment by dfee** [comment]
@qwexvf you can use the `on_close` method of `WebsocketConnectionView` to do tear down, and publish to a channel.

**Comment by qwexvf** [comment]
@dfee thats exactly what i'm doing here
```
@asyncio.coroutine
    def on_close(self):
        print("Disconnected: ", self)
        self.client.publish(self.room, json.dumps({'type': 'leave', }))
        self.pubsub.unsubscribe(self.room)
        self.request.session['subscribed'] = None
        self.thread.stop()
```
but its says that socket is already closed.....

**Comment by dfee** [comment]
I'm not sure the `self.thread.stop()` is a) necessary, or b) a good idea. Maybe @housleyjk could weigh in on that.

My understanding is that your async view is run in the main thread, while sync views are run in executors (by default, that's a [ThreadPoolExecutor](https://docs.python.org/3/library/asyncio-eventloop.html#executor)). I guess if you're spawning a separate thread, you could call `.stop()`. I'm not sure why you are doing that, though.

Now, for your publish – what is `self.client`? Is that a redis client? And if so, you probably shouldn't be doing that in an async view. Either you should be using an executor to publish that or use `asyncio-redis` and await the result.

You say that "socket is closed". If we're to assume the websocket, then of course it's closed. If we're to assume the redis connection, I can't provide guidance, because unless you've disconnected it, it ought to still be open. It could be due to how you're implementing your redis client…

**Comment by qwexvf** [comment]
@dfee thank you.
the truth is this code was for tornado' websocket. so i used this code on pyramid.
ill try something new with asyncio-redis then, ill report the result soon.
sorry for the I know I'm bugging you guys but please help thanks !

**Comment by dfee** [comment]
Based on @housleyjk's thoughts about `sqlalchemy` not being (any / much) slower then `aiopg` when using an executor, I extended that idea to mean that I might as well stick with standard `redis-py`.

In addition, I'm attempting to move away from Redis to PostgreSQL for my pubsub – [marginally slower](https://gist.github.com/fcurella/3490031) but worth the reduced overhead in scaling.
